// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoG5zU8EzdPPFrXFstx0licFDklaxs83M',
    appId: '1:974459699084:web:8d47fa11d39ca31968a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    authDomain: 'elimisha-90787.firebaseapp.com',
    databaseURL: 'https://elimisha-90787-default-rtdb.firebaseio.com',
    storageBucket: 'elimisha-90787.firebasestorage.app',
    measurementId: 'G-YBP1DZ3VC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_t14ixbvACi7Bk2wiEQ6lWOG7MFd61iI',
    appId: '1:974459699084:android:af7b6d0c3b9f29ed68a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    databaseURL: 'https://elimisha-90787-default-rtdb.firebaseio.com',
    storageBucket: 'elimisha-90787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vaTsgPgH1Rdp5ms8ehbgVB0tNa379eE',
    appId: '1:974459699084:ios:fadbe5b61df6314d68a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    databaseURL: 'https://elimisha-90787-default-rtdb.firebaseio.com',
    storageBucket: 'elimisha-90787.firebasestorage.app',
    androidClientId: '974459699084-a4l85cq72vu4gr90glvsefnmod4sccq6.apps.googleusercontent.com',
    iosClientId: '974459699084-bielbsmm5r5b6g99kd705smclfafmr1c.apps.googleusercontent.com',
    iosBundleId: 'com.topscoreapp.ai',
  );

}